### ISSUE TITLE
why use h3 tag hehe ?

### ISSUE THREAD

**Issue by fusco** [FrancisClerfayt/projetFallOut#2]
https://github.com/FrancisClerfayt/projetFallOut/blob/6c6adf679c2fce181465c3e00848d0e799ca46b6/index.html#L45

**Comment by FrancisClerfayt** [comment]
could have used a paragraph. I just put an h3 since font size was lower than h2 but higher than than regular text.

**Comment by FrancisClerfayt** [comment]
changed the h3 into a paragraph with a class to change the font-size.
